import type { Course, CourseDetails } from '@/plugins/fake-api/handlers/apps/academy/types'

import avatar1 from '@images/avatars/avatar-1.png'
import avatar12 from '@images/avatars/avatar-12.png'
import avatar13 from '@images/avatars/avatar-13.png'
import avatar14 from '@images/avatars/avatar-14.png'
import avatar15 from '@images/avatars/avatar-15.png'
import avatar2 from '@images/avatars/avatar-2.png'
import avatar3 from '@images/avatars/avatar-3.png'
import avatar5 from '@images/avatars/avatar-5.png'
import avatar6 from '@images/avatars/avatar-6.png'
import avatar8 from '@images/avatars/avatar-8.png'
import avatar9 from '@images/avatars/avatar-9.png'

import tutorImg1 from '@images/pages/app-academy-tutor-1.png'
import tutorImg2 from '@images/pages/app-academy-tutor-2.png'
import tutorImg3 from '@images/pages/app-academy-tutor-3.png'
import tutorImg4 from '@images/pages/app-academy-tutor-4.png'
import tutorImg5 from '@images/pages/app-academy-tutor-5.png'
import tutorImg6 from '@images/pages/app-academy-tutor-6.png'

interface DB {
  courses: Course[]
  courseDetails: CourseDetails
}

export const db: DB = {
  courses: [
    {
      id: 1,
      user: 'مریم رضایی',
      image: avatar1,
      tutorImg: tutorImg1,
      completedTasks: 19,
      totalTasks: 25,
      userCount: 18,
      note: 20,
      view: 83,
      time: '۱۷ ساعت و ۳۴ دقیقه',
      logo: 'ri-angularjs-line',
      color: 'error',
      courseTitle: 'اصول برنامه‌نویسی انگولار',
      desc: 'دوره مقدماتی برای یادگیری انگولار و اصول برنامه‌نویسی با تایپ‌اسکریپت',
      tags: 'Web',
      rating: 4.4,
      ratingCount: 8,
    },
    {
      id: 2,
    user: 'علی احمدی',
    tutorImg: tutorImg2,
    image: avatar2,
    completedTasks: 48,
    totalTasks: 52,
    userCount: 14,
    note: 48,
    view: 43,
    time: '۱۹ ساعت و ۱۷ دقیقه',
    logo: 'ri-palette-line',
    color: 'warning',
    courseTitle: 'طراحی اپلیکیشن با فیگما',
    desc: 'یادگیری طراحی اپلیکیشن‌های زیبا و کاربرپسند با استفاده از فیگما',
    tags: 'Design',
    rating: 4.9,
    ratingCount: 10,
  },
  {
    id: 3,
    user: 'زهرا موسوی',
    image: avatar2,
    tutorImg: tutorImg3,
    completedTasks: 87,
    totalTasks: 100,
    userCount: 19,
    note: 81,
    view: 88,
    time: '۱۶ ساعت و ۱۶ دقیقه',
    logo: 'ri-reactjs-line',
    color: 'info',
    courseTitle: 'توسعه وب با ری‌اکت',
    desc: 'دوره‌ای برای یادگیری توسعه اپلیکیشن‌های پویا با استفاده از ری‌اکت جی‌اس',
    tags: 'Web',
    rating: 4.8,
    ratingCount: 9,
    },
    {
      id: 4,
    user: 'سارا رضوی',
    image: avatar3,
    completedTasks: 33,
    tutorImg: tutorImg4,
    totalTasks: 50,
    userCount: 28,
    note: 21,
    view: 87,
    time: '۱۵ ساعت و ۴۹ دقیقه',
    logo: 'ri-pencil-line',
    color: 'success',
    courseTitle: 'آموزش هنر و طراحی',
    desc: 'ویدیوها و راهنماهای ساده که به شما نحوه طراحی حیوانات و انسان‌ها را آموزش می‌دهند.',
    tags: 'Design',
    rating: 4.7,
    ratingCount: 18,
  },
  {
    id: 5,
    user: 'حسین کریمی',
    tutorImg: tutorImg5,
    image: avatar14,
    completedTasks: 100,
    totalTasks: 100,
    userCount: 13,
    note: 19,
    view: 13,
    time: '۱۲ ساعت و ۴۲ دقیقه',
    logo: 'ri-star-smile-line',
    color: 'primary',
    courseTitle: 'مبانی اولیه برنامه‌نویسی',
    desc: 'یادگیری مبانی اساسی محبوب‌ترین زبان برنامه‌نویسی.',
    tags: 'Web',
    rating: 4.6,
    ratingCount: 11,
  },
  {
    id: 6,
    user: 'زهرا عباسی',
    tutorImg: tutorImg6,
    image: avatar3,
    completedTasks: 23,
    totalTasks: 25,
    userCount: 78,
    note: 36,
    view: 36,
    time: '۱ ساعت و ۴۲ دقیقه',
    logo: 'ri-reactjs-line',
    color: 'info',
    courseTitle: 'ری‌اکت برای مبتدیان',
    desc: 'ری‌اکت را تنها در چند جلسه فشرده با این دوره جامع بیاموزید.',
    tags: 'Web',
    rating: 4.5,
    ratingCount: 68,
  },
  {
    id: 7,
    user: 'محمد نادری',
    tutorImg: tutorImg1,
    image: avatar14,
    completedTasks: 11,
    totalTasks: 20,
    userCount: 74,
    note: 21,
    view: 60,
    time: '۴ ساعت و ۵۹ دقیقه',
    logo: 'ri-star-smile-line',
    color: 'primary',
    courseTitle: 'علم تفکر انتقادی',
    desc: 'بیاموزید چگونه استدلال‌های خود را بهبود دهید و تصمیمات بهتری بگیرید.',
    tags: 'Psychology',
    rating: 4.4,
    ratingCount: 64,
  },
  {
    id: 8,
    user: 'مهسا یوسفی',
    tutorImg: tutorImg2,
    image: avatar1,
    completedTasks: 6,
    totalTasks: 25,
    userCount: 44,
    note: 28,
    view: 13,
    time: '۲ ساعت و ۹ دقیقه',
    logo: 'ri-palette-line',
    color: 'warning',
    courseTitle: 'دوره کامل طراحی UI/UX با فیگما',
    desc: 'یادگیری طراحی اپلیکیشن‌های زیبا و جذاب موبایل با فیگما.',
    tags: 'UI/UX',
    rating: 4.3,
    ratingCount: 34,
    },
    {
      id: 9,
    user: 'رضا توکلی',
    tutorImg: tutorImg3,
    image: avatar8,
    completedTasks: 67,
    totalTasks: 100,
    userCount: 95,
    note: 34,
    view: 26,
    time: '۲۲ ساعت و ۲۱ دقیقه',
    logo: 'ri-star-smile-line',
    color: 'primary',
    courseTitle: 'تکنیک‌های پیشرفته حل مسئله',
    desc: 'با این دوره جامع، یاد بگیرید چگونه مثل یک حرفه‌ای مشکلات را حل کنید.',
    tags: 'Psychology',
    rating: 4.2,
    ratingCount: 85,
  },
  {
    id: 10,
    user: 'علیرضا جوادی',
    image: avatar1,
    completedTasks: 49,
    totalTasks: 50,
    tutorImg: tutorImg4,
    userCount: 98,
    note: 51,
    view: 37,
    time: '۲۲ ساعت و ۲۲ دقیقه',
    logo: 'ri-reactjs-line',
    color: 'info',
    courseTitle: 'پیشرفته ری‌اکت نیتیو',
    desc: 'با این دوره جامع، یاد بگیرید چگونه محبوب‌ترین سیستم عامل موبایل را بسازید.',
    tags: 'Web',
    rating: 4.1,
    ratingCount: 88,
  },
  {
    id: 11,
    user: 'زهرا ملکی',
    image: avatar9,
    completedTasks: 87,
    totalTasks: 100,
    tutorImg: tutorImg5,
    userCount: 19,
    note: 40,
    view: 32,
    time: '۱۵ ساعت و ۲۵ دقیقه',
    logo: 'ri-reactjs-line',
    color: 'info',
    courseTitle: 'ساخت اپلیکیشن‌های وب با ری‌اکت',
    desc: 'ساخت اپلیکیشن‌های مدرن وب با استفاده از ری‌اکت و ریداکس را یاد بگیرید.',
    tags: 'Web',
    rating: 4.0,
    ratingCount: 9,
  },
  {
    id: 12,
    user: 'مریم یوسفی',
    image: avatar1,
    tutorImg: tutorImg6,
    completedTasks: 22,
    totalTasks: 25,
    userCount: 26,
    note: 22,
    view: 77,
    time: '۴ ساعت و ۳۳ دقیقه',
    logo: 'ri-angularjs-line',
    color: 'error',
    courseTitle: 'مسیریابی و ناوبری در انگولار',
    desc: 'با این دوره جامع، ساخت اپلیکیشن‌های تک‌صفحه‌ای حرفه‌ای را یاد بگیرید.',
    tags: 'Web',
    rating: 3.9,
    ratingCount: 16,
  },
  {
    id: 13,
    user: 'محمد امینی',
    image: avatar15,
    tutorImg: tutorImg1,
    completedTasks: 11,
    totalTasks: 50,
    userCount: 78,
    note: 75,
    view: 87,
    time: '۱۶ ساعت و ۳۸ دقیقه',
    logo: 'ri-star-smile-line',
    color: 'primary',
    courseTitle: 'حل خلاقانه مسائل',
    desc: 'با این دوره جامع، یاد بگیرید چگونه مسائل را خلاقانه و مؤثر حل کنید.',
    tags: 'Psychology',
    rating: 3.8,
    ratingCount: 68,
    },
    {
      id: 14,
    user: 'مهدی احمدی',
    image: avatar2,
    tutorImg: tutorImg2,
    completedTasks: 11,
    totalTasks: 25,
    userCount: 92,
    note: 39,
    view: 60,
    time: '۲۲ ساعت و ۴۳ دقیقه',
    logo: 'ri-angularjs-line',
    color: 'error',
    courseTitle: 'ساخت اپلیکیشن‌های وب با انگولار',
    desc: 'یاد بگیرید چگونه اپلیکیشن‌های وب مدرن را با انگولار و تایپ‌اسکریپت بسازید.',
    tags: 'Web',
    rating: 3.7,
    ratingCount: 82,
  },
  {
    id: 15,
    user: 'زهرا حسینی',
    image: avatar12,
    tutorImg: tutorImg3,
    completedTasks: 4,
    totalTasks: 5,
    userCount: 14,
    note: 22,
    view: 51,
    time: '۲ ساعت و ۲۹ دقیقه',
    logo: 'ri-angularjs-line',
    color: 'error',
    courseTitle: 'انگولار پیشرفته',
    desc: 'یاد بگیرید چگونه اپلیکیشن‌های وب مدرن را با انگولار و تایپ‌اسکریپت بسازید.',
    tags: 'Web',
    rating: 3.6,
    ratingCount: 12,
  },
  {
    id: 16,
    user: 'سینا رضوی',
    image: avatar1,
    tutorImg: tutorImg4,
    completedTasks: 22,
    totalTasks: 25,
    userCount: 20,
    note: 12,
    view: 95,
    time: '۲۰ ساعت و ۱۰ دقیقه',
    logo: 'ri-reactjs-line',
    color: 'info',
    courseTitle: 'تست ری‌اکت با Jest و Enzyme',
    desc: 'یاد بگیرید چگونه اپلیکیشن‌های مدرن وب را با ری‌اکت و ریداکس تست کنید.',
    tags: 'Web',
    rating: 3.5,
    ratingCount: 10,
  },
  {
    id: 17,
    user: 'محمد موسوی',
    image: avatar13,
    tutorImg: tutorImg5,
    completedTasks: 11,
    totalTasks: 50,
    userCount: 29,
    note: 20,
    view: 98,
    time: '۱۶ ساعت و ۱۵ دقیقه',
    logo: 'ri-palette-line',
    color: 'warning',
    courseTitle: 'نظریه تایپوگرافی',
    desc: 'اصول و تئوری تایپوگرافی برای طراحی جذاب و خلاقانه را یاد بگیرید.',
    tags: 'Design',
    rating: 3.4,
    ratingCount: 19,
  },
  {
    id: 18,
    user: 'علیرضا نوری',
    image: avatar1,
    completedTasks: 23,
    tutorImg: tutorImg6,
    totalTasks: 100,
    userCount: 20,
    note: 16,
    view: 77,
    time: '۴ ساعت و ۳۱ دقیقه',
    logo: 'ri-angularjs-line',
    color: 'error',
    courseTitle: 'تست انگولار',
    desc: 'یاد بگیرید چگونه اپلیکیشن‌های وب مدرن را با انگولار و تایپ‌اسکریپت تست کنید.',
    tags: 'Web',
    rating: 4.3,
    ratingCount: 10,
    },
    {
      id: 19,
    user: 'حسین عباسی',
    image: avatar8,
    completedTasks: 17,
    tutorImg: tutorImg1,
    totalTasks: 50,
    userCount: 28,
    note: 91,
    view: 31,
    time: '۱ ساعت و ۵۲ دقیقه',
    logo: 'ri-reactjs-line',
    color: 'info',
    courseTitle: 'ری‌اکت برای حرفه‌ای‌ها',
    desc: 'یاد بگیرید چگونه اپلیکیشن‌های وب مدرن را با ری‌اکت و ریداکس بسازید.',
    tags: 'Web',
    rating: 4.2,
    ratingCount: 18,
  },
  {
    id: 20,
    user: 'زهرا نظری',
    image: avatar12,
    tutorImg: tutorImg2,
    completedTasks: 1,
    totalTasks: 10,
    userCount: 11,
    note: 33,
    view: 53,
    time: '۱۶ ساعت و ۲۴ دقیقه',
    logo: 'ri-pencil-line',
    color: 'success',
    courseTitle: 'دوره جامع طراحی',
    desc: 'با این دوره جامع، نحوه طراحی حرفه‌ای را یاد بگیرید.',
    tags: 'Art',
    rating: 4.1,
    ratingCount: 9,
  },
  {
    id: 21,
    user: 'علی شریفی',
    image: avatar2,
    completedTasks: 91,
    totalTasks: 100,
    tutorImg: tutorImg3,
    userCount: 11,
    note: 17,
    view: 74,
    time: '۵ ساعت و ۵۷ دقیقه',
    logo: 'ri-angularjs-line',
    color: 'error',
    courseTitle: 'مبانی انگولار',
    desc: 'دوره مقدماتی برای یادگیری انگولار و اصول چارچوب با تایپ‌اسکریپت.',
    tags: 'Web',
    rating: 4.0,
    ratingCount: 7,
  },
  {
    id: 22,
    user: 'فاطمه میرزایی',
    image: avatar1,
    tutorImg: tutorImg4,
    completedTasks: 49,
    totalTasks: 50,
    userCount: 28,
    note: 30,
    view: 54,
    time: '۴ ساعت و ۴۰ دقیقه',
    logo: 'ri-pencil-line',
    color: 'success',
    courseTitle: 'مقدمه‌ای بر نقاشی دیجیتال',
    desc: 'با این دوره جامع، نحوه طراحی حرفه‌ای را یاد بگیرید.',
    tags: 'Art',
    rating: 3.9,
    ratingCount: 18,
  },
  {
    id: 23,
    user: 'محمد طاهری',
    image: avatar5,
    tutorImg: tutorImg5,
    completedTasks: 81,
    totalTasks: 100,
    userCount: 79,
    note: 46,
    view: 27,
    time: '۸ ساعت و ۴۴ دقیقه',
    logo: 'ri-star-smile-line',
    color: 'primary',
    courseTitle: 'علم تفکر در زندگی روزمره',
    desc: 'یاد بگیرید چگونه بهتر فکر کنید، بهتر بحث کنید، و انتخاب‌های بهتری داشته باشید.',
    tags: 'Psychology',
    rating: 3.8,
    ratingCount: 69,
    },
    {
      id: 24,
    user: 'لیلا جعفری',
    image: avatar13,
    completedTasks: 6,
    tutorImg: tutorImg6,
    totalTasks: 25,
    userCount: 28,
    note: 11,
    view: 77,
    time: '۲۲ ساعت و ۳۶ دقیقه',
    logo: 'ri-pencil-line',
    color: 'success',
    courseTitle: 'تئوری رنگ',
    desc: 'یاد بگیرید چگونه مانند یک حرفه‌ای از رنگ استفاده کنید.',
    tags: 'Design',
    rating: 3.7,
    ratingCount: 18,
  },
  {
    id: 25,
    user: 'نگار لاوی',
    image: avatar6,
    completedTasks: 13,
    totalTasks: 100,
    tutorImg: tutorImg1,
    userCount: 93,
    note: 73,
    view: 67,
    time: '۱۹ ساعت و ۲۱ دقیقه',
    logo: 'ri-palette-line',
    color: 'warning',
    courseTitle: 'دوره جامع فیگما',
    desc: 'یاد بگیرید چگونه یک اپلیکیشن موبایل زیبا و جذاب طراحی کنید.',
    tags: 'UI/UX',
    rating: 3.6,
    ratingCount: 83,
    },
  ],

  courseDetails: {
    title: 'مبانی اولیه UI/UX',
    about: 'طراحی وب را در یک ساعت با بیش از ۲۵ قانون و راهنمای ساده یاد بگیرید — همراه با منابع فوق‌العاده طراحی وب!',
    instructor: 'رضا احمدی',
    instructorAvatar: avatar1,
    instructorPosition: 'توسعه‌دهنده وب، طراح و مدرس',
    skillLevel: 'تمام سطوح',
    totalStudents: 38815,
    language: 'فارسی',
    isCaptions: true,
    length: '۱.۵ ساعت کلی',
    totalLectures: 19,
    description: `
      <p class="text-body-1">
        محتوای این دوره همچنین در دوره دیگر من درباره طراحی وب و توسعه با HTML5 و CSS3 پوشش داده شده است. برای بررسی آن دوره، به پایین همین صفحه بروید! اگر در حال حاضر دوره دیگر من را می‌گذرانید، شما تمام آنچه لازم است برای شروع طراحی وب‌سایت‌های زیبا دارید!
      </p>
  
      <p class="text-body-1">
        "بهترین دوره طراحی وب: اگر به طراحی وب علاقه دارید و به دنبال چیزی بیشتر از یک دوره «چگونه از وردپرس استفاده کنیم» هستید، من این دوره را به شدت توصیه می‌کنم." — فلوریان جیستی
      </p>
  
      <p class="text-body-1">
        "بسیار مفید برای افرادی که چپ‌مغز هستند: من با HTML، CSS، jQuery و Twitter Bootstrap آشنا بودم، اما به آموزش طراحی وب نیاز داشتم. این دوره تکنیک‌های عملی و تاثیرگذاری برای زیباتر و جذاب‌تر کردن وب‌سایت‌ها به من ارائه کرد." — سوزان دارلین کین
      </p>`,
    content: [
      {
        title: 'محتوای دوره',
        status: '2 / 5',
        time: '۴.۴ دقیقه',
        id: 'section1',
        topics: [
          { title: '۱. خوش‌آمد به این دوره', time: '۲.۴ دقیقه', isCompleted: true },
          { title: '۲. قبل از شروع تماشا کنید', time: '۴.۸ دقیقه', isCompleted: true },
          { title: '۳. نظریه پایه طراحی', time: '۵.۹ دقیقه', isCompleted: false },
          { title: '۴. اصول اولیه', time: '۳.۶ دقیقه', isCompleted: false },
          { title: '۵. UI/UX چیست', time: '۱۰.۶ دقیقه', isCompleted: false },
        ],
      },
      {
        title: 'طراحی وب برای توسعه‌دهندگان',
        status: '0 / 4',
        time: '۴.۸ دقیقه',
        id: 'section2',
        topics: [
          { title: '۱. چگونه از Pages در فیگما استفاده کنیم', time: '۸:۳۱ دقیقه', isCompleted: false },
          { title: '۲. Wireframe Lo Fi چیست', time: '۲ دقیقه', isCompleted: false },
          { title: '۳. چگونه در فیگما از رنگ استفاده کنیم', time: '۵.۹ دقیقه', isCompleted: false },
          { title: '۴. تفاوت Frames و Groups در فیگما', time: '۳.۶ دقیقه', isCompleted: false },
        ],
      },
      {
        title: 'ساخت وب‌سایت‌های زیبا!',
        status: '0 / 4',
        time: '۴.۴ دقیقه',
        id: 'section3',
        topics: [
          { title: '۱. بلوک Section و Div', time: '۳:۵۳ دقیقه', isCompleted: false },
          { title: '۲. نسخه فقط‌خواندنی اپلیکیشن چت', time: '۲:۰۳ دقیقه', isCompleted: false },
          { title: '۳. ذخیره خودکار در Webflow', time: '۸ دقیقه', isCompleted: false },
          { title: '۴. تنظیمات Canvas', time: '۳ دقیقه', isCompleted: false },
          { title: '۵. تگ‌های HTML', time: '۱۰ دقیقه', isCompleted: false },
          { title: '۶. فوتر (اپلیکیشن چت)', time: '۹:۱۰ دقیقه', isCompleted: false },
        ],
      },
      {
        title: 'پروژه نهایی',
        status: '0 / 3',
        time: '۴.۴ دقیقه',
        id: 'section4',
        topics: [
          { title: '۱. سایت وبلاگ ریسپانسیو', time: '۱۰:۰۰ دقیقه', isCompleted: false },
          { title: '۲. پورتفولیوی ریسپانسیو', time: '۱۳:۰۰ دقیقه', isCompleted: false },
          { title: '۳. نظریه پایه طراحی', time: '۱۵ دقیقه', isCompleted: false },
        ],
      },
    ],
  },  
}
